# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish GH Pages

on:
  workflow_dispatch:
  push:
    branches: [ "gh-pages" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    
    - run: npm install
    - run: npm install --save gh-pages
    - run: npx browserslist@latest --update-db
    - run: npm run deploy
