# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish GH Pages

on:
  workflow_dispatch:
  push:
    branches: [ "gh-pages" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Setup git identity
      run: |
          git config --global user.name 'Arturo Vidal'
          git config --global user.email 'arturo.vidal.96@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    
    - run: npm ci
    - run: npm install --save gh-pages
    - run: npx browserslist@latest --update-db
    # - run: npm run deploy
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d src -u "github-actions-bot <support+actions@github.com>"
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
