name: Update Obsidian pages

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Python 3.10
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run python to update Obsidian Pages
        run: python CosmereWiki.py

      - name: Run python to update Wiki Nodes
        run: python WikiToNodes.py
        
